"""ติดตั้ง academicforward เป็นคำสั่งเดียว /academicforward ใน Antigravity — รันใหม่ทุกครั้งที่เพิ่ม/เปลี่ยนสกิล

แหล่งจริงเดียว = academicforward/.claude/commands/*.md (มีบรรทัด @<path คู่มือ>)
ผลลัพธ์ = ~/.gemini/config/skills/academicforward/SKILL.md (global skill ของ Antigravity = slash command)
คำสั่งเดียวเลือกคู่มือให้เองตามงานที่ผู้ใช้พิมพ์ ชี้ไปคู่มือเต็มด้วย path จริง ไม่คัดลอกเนื้อหา

    python gen-antigravity.py
"""
import re
import shutil
from pathlib import Path
import sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

HERE = Path(__file__).resolve().parent
AF = HERE if (HERE / ".claude" / "commands").is_dir() else (Path.home() / "Documents" / "GitHub" / "academicforward")
OUT = Path.home() / ".gemini" / "config" / "skills"
NAME = "academicforward"
MARK = "<!-- generated by claude-config/gen-antigravity.py -->"

HEAD = f"""---
name: {NAME}
description: ศูนย์รวมสกิลวิชาการ AcademicForward ของ มรนว. — วิจัย ป.ตรี/ป.โท-เอก, manuscript วารสาร, เขียนตำรา, ขัดภาษาไทยวิชาการ, ตรวจข้ออ้าง-หลักฐาน, สืบค้น Scopus/TCI, สไลด์, ผังงาน, WP/WI, ภาพโพสต์, โพสต์ Facebook ARITC, ไฟล์ Word, ขอตำแหน่ง, KPI. Use when the user invokes /{NAME} or asks for any academic writing, research, design, publishing or document-automation task covered by these manuals.
---
{MARK}

# /{NAME}

คำสั่งเดียวครอบทุกสกิลใน `{AF.as_posix()}` — ข้อความที่ผู้ใช้พิมพ์ต่อท้าย /{NAME} คืองานที่ต้องการ

## วิธีทำงาน

1. อ่านงานที่ผู้ใช้ต้องการ แล้วเลือกโหมดจากตารางด้านล่าง (ผู้ใช้อาจพิมพ์ชื่อโหมดหรือเลขข้อมาเลย)
2. ถ้างานตรงหลายโหมด ให้ดูตาราง "คอมโบ" ใน `{AF.as_posix()}/README.md` แล้วทำตามลำดับ เริ่มจากโหมดแรกที่ยังไม่ได้ทำ
3. ถ้าไม่มีข้อความต่อท้าย หรือไม่ชัดว่าเป็นโหมดไหน ให้แสดงเมนูตารางนี้ (เลข + ชื่อ + คำอธิบาย) แล้วถามผู้ใช้ก่อน ห้ามเดา
4. เลือกได้แล้ว ให้อ่านไฟล์คู่มือของโหมดนั้นให้ครบทุกไฟล์ทั้งไฟล์ ก่อนเริ่มงาน แล้วปฏิบัติตามกฎและด่านตรวจในคู่มืออย่างเคร่งครัด
5. บอกผู้ใช้สั้น ๆ ว่ากำลังใช้โหมดไหน
6. อ่าน `{AF.as_posix()}/AGENTS.md` ด้วย — กติกาส่งงานต่อข้าม agent/ข้ามเครื่อง (memory ไม่แชร์กัน กฎใหม่และงานค้างต้องเขียนลงไฟล์ แก้ repo แล้ว commit + push)

## โหมด

| # | โหมด | ใช้เมื่อ | ข้อมูลที่ควรได้จากผู้ใช้ | คู่มือที่ต้องอ่าน |
|---|---|---|---|---|
"""


def field(text, name):
    m = re.search(rf"^{name}:\s*(.+)$", text, re.M)
    return m.group(1).strip() if m else ""


def cell(s):
    return s.replace("|", "/")


def main():
    src = AF / ".claude" / "commands"
    if not src.is_dir():
        raise SystemExit(f"ไม่พบ {src} — clone academicforward ไว้ที่ ~/Documents/GitHub ก่อน")
    rows = []
    for f in sorted(src.glob("*.md")):
        text = f.read_text(encoding="utf-8")
        refs = re.findall(r"^@(\S+\.md)", text, re.M)
        missing = [p for p in refs if not (AF / p).is_file()]
        if not refs or missing:
            print(f"ข้าม {f.name} ({'ไม่พบ ' + ', '.join(missing) if missing else 'ไม่มีบรรทัด @path'})")
            continue
        paths = "<br>".join(f"`{(AF / p).as_posix()}`" for p in refs)
        rows.append(f"| {len(rows) + 1} | {f.stem} | {cell(field(text, 'description'))} "
                    f"| {cell(field(text, 'argument-hint'))} | {paths} |")
        print(f"ok  {f.stem}")

    # ลบคำสั่งย่อยรายตัวที่สคริปต์รุ่นก่อนสร้างไว้
    for d in OUT.glob("*/SKILL.md"):
        link = d.parent.is_symlink() or getattr(d.parent, "is_junction", lambda: False)()
        if d.parent.name != NAME and not link and MARK in d.read_text(encoding="utf-8"):
            shutil.rmtree(d.parent)
            print(f"ลบคำสั่งเก่า /{d.parent.name}")

    target = OUT / NAME / "SKILL.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(HEAD + "\n".join(rows) + "\n", encoding="utf-8", newline="\n")
    print(f"ติดตั้ง /{NAME} ({len(rows)} โหมด) -> {target}")

    # คำสั่งเดียวกันสำหรับ Claude Code (~/.claude/commands = junction ไป claude-config/commands)
    claude = Path.home() / ".claude" / "commands" / f"{NAME}.md"
    if claude.parent.is_dir():
        body = HEAD.split("---", 2)[2].replace(MARK + "\n", "").lstrip()
        claude.write_text(
            "---\ndescription: ศูนย์รวมสกิลวิชาการ AcademicForward — เลือกคู่มือให้เองตามงาน (วิจัย เขียนตำรา ขัดภาษา สืบค้น สไลด์ ผังงาน โพสต์ Word KPI)\n"
            "argument-hint: [งานที่ต้องการ / เลขหรือชื่อโหมด]\n---\n"
            f"{MARK}\n\n" + body + "\n".join(rows)
            + "\n\nงานที่ผู้ใช้ต้องการ: $ARGUMENTS\n",
            encoding="utf-8", newline="\n",
        )
        print(f"ติดตั้ง /{NAME} ใน Claude Code -> {claude}")


if __name__ == "__main__":
    main()
