"""ติดตั้ง academicforward + desk-utils เป็นคำสั่งเดียว /academicforward ใน Antigravity และ Claude Code

แหล่งจริง:
- academicforward/.claude/commands/*.md (คู่มือวิชาการ 22 โหมด)
- desk-utils/tools/*/SKILL.md (เครื่องมือเดสก์ท็อป photo-post, file-organizer, วิดีโอ)

ผลลัพธ์:
- ~/.gemini/config/skills/academicforward/SKILL.md (global skill ครอบทุกงานและต่อสายสกิลข้ามระบบได้)
- ~/.claude/commands/academicforward.md สำหรับ Claude Code

    python gen-antigravity.py
"""
import os
import re
import shutil
from pathlib import Path
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

HERE = Path(__file__).resolve().parent
AF = HERE if (HERE / ".claude" / "commands").is_dir() else (Path.home() / "Documents" / "GitHub" / "academicforward")
DU = Path.home() / "Documents" / "GitHub" / "desk-utils"
OUT = Path.home() / ".gemini" / "config" / "skills"
NAME = "academicforward"
OLD_ALIAS = "academicfw"  # ชื่อย่อที่เลิกใช้ — สคริปต์ลบทิ้งให้ทุกเครื่อง
MARK = "<!-- generated by gen-antigravity.py -->"

HEAD = f"""---
name: {NAME}
description: ศูนย์รวมสกิล AcademicForward + Desk-Utils (มรนว.) — วิจัย ป.ตรี/ป.โท-เอก, manuscript วารสาร, เขียนตำรา, ขัดภาษาไทยวิชาการ, ตรวจข้ออ้าง-หลักฐาน, สืบค้น Scopus/TCI, สไลด์, ผังงาน, WP/WI, คัดรูปกิจกรรม photo-post, ทำโพสต์ Facebook ARITC, ไฟล์ Word, จัดระเบียบไฟล์, ตัดต่อวิดีโอ, ขอตำแหน่ง, KPI. Use when the user invokes /{NAME} or asks for any academic or desk automation workflow.
---
{MARK}

# /{NAME}

คำสั่งเดียวครอบทุกสกิลใน `{AF.as_posix()}` และเครื่องมือใน `{DU.as_posix()}` — ข้อความที่ผู้ใช้พิมพ์ต่อท้าย /{NAME} คืองานที่ต้องการ

## วิธีทำงาน

1. อ่านงานที่ผู้ใช้ต้องการ แล้วเลือกโหมดจากตารางด้านล่าง (ผู้ใช้อาจพิมพ์ชื่อโหมดหรือเลขข้อมาเลย)
2. ถ้างานตรงหลายโหมด ให้ดูตาราง "คอมโบ" ใน `{AF.as_posix()}/README.md` หรือสายงานเชื่อมต่อด้านล่าง แล้วทำตามลำดับ เริ่มจากโหมดแรกที่ยังไม่ได้ทำ
3. ถ้าไม่มีข้อความต่อท้าย หรือไม่ชัดว่าเป็นโหมดไหน ให้แสดงเมนูตารางนี้ (เลข + ชื่อ + คำอธิบาย) แล้วถามผู้ใช้ก่อน ห้ามเดา
4. เลือกได้แล้ว ให้อ่านไฟล์คู่มือของโหมดนั้นให้ครบทุกไฟล์ทั้งไฟล์ ก่อนเริ่มงาน แล้วปฏิบัติตามกฎและด่านตรวจในคู่มืออย่างเคร่งครัด
5. บอกผู้ใช้สั้น ๆ ว่ากำลังใช้โหมดไหน
6. อ่าน `{AF.as_posix()}/AGENTS.md` ด้วย — กติกาส่งงานต่อข้าม agent/ข้ามเครื่อง (memory ไม่แชร์กัน กฎใหม่และงานค้างต้องเขียนลงไฟล์ แก้ repo แล้ว commit + push)
7. **รันคำสั่ง Python ในเครื่องได้ทันที:** หากงานหรือโหมดนั้นระบุให้รันสคริปต์ เช่น `py -X utf8 -m photo_post scan ...` (ใน desk-utils) หรือสคริปต์ใน `Automation/scripts/` / `Designing/scripts/` ให้ AI เรียกเครื่องมือเชลล์ (Terminal / run_command) รันคำสั่ง Python บนเครื่องได้ทันทีอัตโนมัติ
8. **ต่อสายงานข้ามสกิลอัตโนมัติ (Multi-skill combos):** เมื่องานครอบคลุมหลายขั้น เช่น คัดรูปกิจกรรม (`photo-post`) ➔ ร่างโพสต์ (`aritc-social-post-agent`) ➔ ทำภาพกราฟิก (`social-graphic-agent`) ➔ บันทึก KPI (`kpi-report`) ให้เชื่อมต่อขั้นตอนทำงานต่อไปจนเสร็จครบวงจร

## สายงานเชื่อมต่อที่พบบ่อย (Combos)

| สายงาน | ลำดับการต่อสกิล | การเชื่อมโยงคำสั่ง |
|---|---|---|
| 📸 **คัดรูปกิจกรรม ➔ โพสต์ ➔ กราฟิก ➔ KPI** | `photo-post` ➔ `aritc-social-post-agent` ➔ `social-graphic-agent` ➔ `kpi-report` | รัน `py -X utf8 -m photo_post scan <โฟลเดอร์>` ใน desk-utils เพื่อคัดรูปและเสนอปก ➔ ร่างโพสต์ Facebook ARITC ➔ ทำกราฟิก ➔ ส่งหลักฐานเข้า Drive & KPI |
| 🎓 **วิจัย ป.ตรี / ป.โท-เอก ครบวงจร** | `academic-search-keywords` ➔ `grad-research` / `undergrad-research` ➔ `argument-auditor` ➔ `prose-cleaner` ➔ `docx-builder` | สืบค้น ➔ ยกร่างเนื้อหา ➔ ตรวจสอบข้ออ้าง ➔ ขัดเกลาภาษา ➔ สคริปต์สร้างไฟล์เล่ม Word |
| ✍️ **ผลิตตำราเรียนทั้งเล่ม** | `textbook-structure-agent` ➔ `textbook-writer` ➔ `textbook-figure-agent` ➔ `docx-builder` ➔ `argument-auditor` ➔ `prose-cleaner` | วางโครงสร้าง ➔ เขียนเนื้อหา ➔ วาดภาพเวกเตอร์ ➔ จัดเล่ม Word ➔ ตรวจและขัดภาษา |
| 🎮 **จัดอบรม / สื่อการสอน ➔ วิดีโอ ➔ KPI** | `slide-hub-agent` ➔ `cutdeck` / `premiere-autocut` ➔ `kpi-report` | สไลด์ PDF 16:9 + ใบงาน A4 + ขึ้นห้อง NoteBoard ➔ ตัดต่อคลิป/เลือกฟุตเทจ ➔ ส่งหลักฐานเข้า Drive & KPI |
| 📁 **ล้างไฟล์ซ้ำ ➔ เตรียมเล่มประเมิน** | `file-organizer` ➔ `docx-safe-edit-agent` ➔ `promote-doc-agent` | สแกนและลบไฟล์ซ้ำ ➔ จัดการไฟล์เอกสารหลักฐาน ➔ กรอกตารางสมรรถนะประเมินชำนาญการ |

## โหมด

### หมวดที่ 1: สกิลวิชาการ (AcademicForward)

| # | โหมด | ใช้เมื่อ | ข้อมูลที่ควรได้จากผู้ใช้ | คู่มือที่ต้องอ่าน |
|---|---|---|---|---|
"""


def field(text, name):
    m = re.search(rf"^{name}:\s*(.+)$", text, re.M)
    return m.group(1).strip() if m else ""


def cell(s):
    return s.replace("|", "/")


def main():
    src = AF / ".claude" / "commands"
    if not src.is_dir():
        raise SystemExit(f"ไม่พบ {src} — clone academicforward ไว้ที่ ~/Documents/GitHub ก่อน")
    rows = []
    for f in sorted(src.glob("*.md")):
        text = f.read_text(encoding="utf-8")
        refs = re.findall(r"^@(\S+\.md)", text, re.M)
        missing = [p for p in refs if not (AF / p).is_file()]
        if not refs or missing:
            print(f"ข้าม {f.name} ({'ไม่พบ ' + ', '.join(missing) if missing else 'ไม่มีบรรทัด @path'})")
            continue
        paths = "<br>".join(f"`{(AF / p).as_posix()}`" for p in refs)
        rows.append(f"| {len(rows) + 1} | {f.stem} | {cell(field(text, 'description'))} "
                    f"| {cell(field(text, 'argument-hint'))} | {paths} |")
        print(f"ok  [academic] {f.stem}")

    # หมวดที่ 2: Desk-Utils Tools
    rows_du = []
    du_tools = [
        ("photo-post", DU / "tools" / "photo_post" / "SKILL.md",
         "คัดรูปกิจกรรม เสนอภาพปก + เรียงเรื่อง ร่างโพสต์ Facebook และลงรูปเป็นหลักฐาน KPI ใน aritc-audit (คำสั่ง: py -X utf8 -m photo_post scan <โฟลเดอร์>)",
         "[โฟลเดอร์รูปภาพกิจกรรม / ชื่องาน]"),
        ("file-organizer", DU / "tools" / "file_organizer" / "SKILL.md",
         "สแกนหาไฟล์ซ้ำ/วิดีโอซ้ำ คลีนชื่อไฟล์ และจัดระเบียบไฟล์ลงถังขยะอย่างปลอดภัย (คำสั่ง: python -u tools/file_organizer/main.py --auto-clean-exact <โฟลเดอร์>)",
         "[โฟลเดอร์หรือไดรฟ์ที่ต้องการสแกน]"),
        ("cutdeck", DU / "tools" / "cutdesk" / "SKILL.md",
         "เปิด UI เลือกช็อตในเบราว์เซอร์ สร้าง Premiere Pro timeline XML + EDL + SRT + MP4 พรีวิว (คำสั่ง: python -m cutdeck <โฟลเดอร์>)",
         "[โฟลเดอร์ฟุตเทจวิดีโอ]"),
        ("premiere-autocut", DU / "tools" / "premierekit" / "SKILL.md",
         "ตัดคลิปอัตโนมัติตามสตอรี่ไลน์ ถอดเสียงด้วย faster-whisper ส่งออก Premiere timeline XML (คำสั่ง: cd tools/premierekit && py -m pkit.transcribe <โฟลเดอร์>)",
         "[สตอรี่ไลน์ / โฟลเดอร์ฟุตเทจ]"),
    ]

    for name, skill_path, desc, hint in du_tools:
        if skill_path.is_file():
            rows_du.append(f"| {len(rows_du) + 1} | {name} | {cell(desc)} | {cell(hint)} | `{(skill_path).as_posix()}` |")
            print(f"ok  [desk-utils] {name}")

    du_section = "\n\n### หมวดที่ 2: เครื่องมือเดสก์ท็อปและสื่อ (Desk-Utils)\n\n" \
                 "| # | โหมด | ใช้เมื่อ | ข้อมูลที่ควรได้จากผู้ใช้ | คู่มือที่ต้องอ่าน |\n" \
                 "|---|---|---|---|---|\n" + "\n".join(rows_du) + "\n"

    # ลบคำสั่งย่อยรายตัวที่สคริปต์รุ่นก่อนสร้างไว้ (เว้น junction)
    for d in OUT.glob("*/SKILL.md"):
        link = d.parent.is_symlink() or getattr(d.parent, "is_junction", lambda: False)()
        if d.parent.name != NAME and not link and MARK in d.read_text(encoding="utf-8"):
            shutil.rmtree(d.parent)
            print(f"ลบคำสั่งเก่า /{d.parent.name}")

    # Antigravity: ติดตั้ง /{NAME}
    target = OUT / NAME / "SKILL.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    full_content = HEAD + "\n".join(rows) + du_section
    target.write_text(full_content, encoding="utf-8", newline="\n")
    print(f"ติดตั้ง /{NAME} ({len(rows)} โหมดวิชาการ + {len(rows_du)} desk-utils) -> {target}")

    # ลบชื่อย่อเก่า /{OLD_ALIAS} ทั้ง Antigravity (junction หรือโฟลเดอร์) และ Claude Code
    old = OUT / OLD_ALIAS
    if old.is_symlink() or getattr(old, "is_junction", lambda: False)():
        os.rmdir(old)  # ลบแค่ลิงก์ ไม่แตะโฟลเดอร์ปลายทาง
    elif (old / "SKILL.md").is_file():
        shutil.rmtree(old)
    old_cmd = Path.home() / ".claude" / "commands" / f"{OLD_ALIAS}.md"
    if old_cmd.is_file():
        old_cmd.unlink()
    if not old.exists():
        print(f"ไม่มีชื่อย่อเก่า /{OLD_ALIAS} แล้ว")

    # Claude Code: (~/.claude/commands/ = junction ไป claude-config/commands)
    claude_dir = Path.home() / ".claude" / "commands"
    if claude_dir.is_dir():
        body = HEAD.split("---", 2)[2].replace(MARK + "\n", "").lstrip()
        claude_content = (
            "---\ndescription: ศูนย์รวมสกิล AcademicForward + Desk-Utils — เลือกคู่มือให้เองตามงาน (วิจัย ตำรา ขัดภาษา สไลด์ ผังงาน photo-post วิดีโอ Word KPI)\n"
            "argument-hint: [งานที่ต้องการ / เลขหรือชื่อโหมด]\n---\n"
            f"{MARK}\n\n" + body + "\n".join(rows) + du_section
            + "\n\nงานที่ผู้ใช้ต้องการ: $ARGUMENTS\n"
        )
        c_file = claude_dir / f"{NAME}.md"
        c_file.write_text(claude_content, encoding="utf-8", newline="\n")
        print(f"ติดตั้ง /{NAME} ใน Claude Code -> {c_file}")


if __name__ == "__main__":
    main()
